server:
  servlet:
    context-path: /
  port: 8081
spring:
  profiles:
    active: dev,redis,security
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8